name: ingenuity_flutter_app_template
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  # STATE MANAGEMENT
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  # LOCALIZATION 
  intl: ^0.19.0
  # AWS AUTH (AWS AMPLIFY + AWS COGNITO)
  amplify_flutter: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  amplify_authenticator: ^2.0.0 # A prebuilt Sign In and Sign Up experience for the Amplify Auth category
  # Flutter Secure Storage provides API to store data in secure storage. 
  # Keychain is used in iOS, 
  # KeyStore based solution is used in Android.
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
